[package]
name = "turbopivot-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
polars = { version = "0.41.0", features = [
    "lazy",
    "temporal",
    "describe",
    "json",
    "parquet",
    "dtype-datetime",
    "dtype-date",
    "dtype-struct",
    "strings",
    "random",
    "object",
    "fmt",
    "performant",
    "pivot",
    "csv",
    "is_in",
    "is_between",
    "regex",
    "concat_str",
] }
thiserror = "2.0.11"
polars-ops = { version = "0.41.0", features = ["pivot", "is_in", "is_between"] }
calamine = "0.26"
chrono = "0.4"
rusqlite = { version = "0.31", features = ["bundled"] }
postgres = "0.19"
